os:
- linux
service:
- docker
language: node_js
node_js:
- stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
dist: trusty
sudo: true
env:
  global:
  - apiKey=$apiKey
  - authDomain=$authDomain
  - databaseURL=$databaseURL
  - projectId=$projectId
  - storageBucket=$storageBucket
  - messagingSenderId=$messagingSenderId
  - MOZ_HEADLESS=1
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - yarn global add @angular/cli
  - yarn global add firebase-tools
install:
- yarn install
jobs:
  include:
  - stage: Tests
    name: Unit Test
    script: yarn travis:test
  - stage: Tests
    if: branch = master
    name: Integration Test
    before_script: yarn travis:webdriver-update
    script: yarn travis:e2e
  - stage: Tests
    if: branch = master
    name: Acceptance Test
    before_script: yarn travis:webdriver-update
    script: yarn travis:cucumber
  - stage: Build
    name: Build App
    script: yarn travis:build
  - stage: Deploy to develop
    name: Deploy App to Heroku (develop)
    if: branch = develop
    script: yarn travis:build
    deploy:
      provider: heroku
      api_key:
        secure: "$HEROKU_API_KEY"
      app: bardock-ng
      local_dir: dist/bardock
      skip_cleanup: true
      on:
        branch: develop
  - stage: Test Develop
    name: Curl to Dev
    if: branch = develop
    script: curl https://bardock-ng.herokuapp.com/
  - stage: deploy to production
    name: Deploy App to Firebase Hosting (master)
    if: branch = master
    script: yarn travis:build
    deploy:
      provider: firebase
      token:
        secure: "LZMDRRXDI+65ShAHHhazOSnxuIRZoZ3NDmiEmmrNiO/hlbo42sJ/DrgRMGvWi01Rc3NJGK5oMiyNGP6ml8yY44bWVG0UhS+pDZ8vz5GHDTnV8FQtPLwuxwzLEwyml8nIDmxz6ndIA5LeThwI9J1YjLxbFDDcwTEsKqC3SKeJ1JUkwkSffcLIsmKfAUyOUdi6COsK6T7GagqTRjZ/9xOhAKX7JzAOHytjM2n8JYJBwZL0VeIs1aabfWfCMyV4nsHf1OJYKhRr1vVYiX6ZbdvcROoDR7va7pmVhD7d8zf3hb2K17LsOgaVCiXbhzO9p8X7/9N2HIvmcvfAsSUJBZH1FWwo/CyVcGBkfCpXrTwgCOjyWPIaUAYGlo/5lOw5xY0jIChewDXmCGTebdGs9/VXrNdTxmE2tBqiUNxBig0Ioc0ef0rvb8Te6tASWMFeWbfuaHRi1mfi9OlcWZ6+vpFMpyh/a9LnPvN57qsZ7OGiPi+MGkfUr6DXILZwGhQkXqFKgceKMAE6i7twQ6jt90k+N04woS1Gx9RzKR9so3wjbIrSUSQlyCc3Md7itceK7PNv9DHp85slwAw1syRIz5ZPnzGmGPL6E5SldiUsSxaPq1dJbUIUIAiIpOnwzCObmWz/Fp8ESH6BtDT1L4Tp/O4oY7NjjEs3tee38zkSml3ZLiw="
      project: "bardock"
      skip_cleanup: true
      on:
        branch: master
    after_success: firebase deploy --token $FIREBASE_API_KEY
  - stage: Test Production
    name: Curl to Prod
    if: branch = master
    script: curl https://bardock-ng.firebaseapp.com/
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - krbaio3@gmail.com
    on_success: never
    on_failure: always
  slack:
    secure: fIYgEhf20QGAbzXhdHT+Xuh1MVKMZbSsCeNu+GreCXNnDJOnAug9/axNGqf7wl0IOaBa2nYPToC//6LIRiUSKBOCxBKFDNya9htuSTGStt2Dlf1xw9YF2EeqjoydgtM9Z6IbfmWQRu4O/KCsxhtISIgr8ZTOTsJaxGyf9hkSjtDmTaqzwlYQGGres8b7yZUqd+XW637OSxlKPNzq/y0gplaQl3j9Pa7u8L94f/QaU6+ErgQxaz+gLdjs3rMWb0u82brM1BGLLNn49iaJn8lV1aq8N+jQAWys7A8uiwQJ7fL4YtqCvsMuEArHRfRDRawCKU6JL5jYfxOfqnttgPhxuirSh/IfD+7hh5q0waBplo78pQJNg5LovmWRKkvkhazv1kLe+0y/v9ulSPkveTlZvTbI180TEP3qRRJAYF2iOjL77Ailq2eZwP0gPu/EJwOyWXi6SlPbk76SIAGTDhP6xR0vx7goXreHJDQeUJ+Hk9SeCzKH6UmGtzaBsvQlzYCvdyJ5NkQJX/kx09fix12dmIIS/6PLn1tEqSByx3+uId9mfcblBWN+ncK1jIAAT/0k1wtNjvjhEIBM+/vZMHsrsza/A0mU8mdDnV85qV8N6oM/ipIr9Nl6ftEquosdH+p9qRUkMe9btCtEJREUKBpIDoivsHY4d5KipzaW44F27jE=
