os:
- linux
service:
- docker
language: node_js
node_js:
- stable
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
dist: trusty
sudo: true
env:
  global:
  - apiKey=$apiKey
  - authDomain=$authDomain
  - databaseURL=$databaseURL
  - projectId=$projectId
  - storageBucket=$storageBucket
  - messagingSenderId=$messagingSenderId
  - MOZ_HEADLESS=1
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- yarn global add @angular/cli
install:
- yarn install
jobs:
  include:
  - stage: Tests
    name: Unit Test
    script: yarn travis:test
  - stage: Tests
    if: branch = master
    name: Integration Test
    before_script: yarn travis:webdriver-update
    script: yarn travis:e2e
  - stage: Tests
    if: branch = master
    name: Acceptance Test
    before_script: yarn travis:webdriver-update
    script: yarn travis:cucumber
  - stage: Build
    name: Build App
    script: yarn travis:build
  - stage: Deploy to develop
    name: Deploy App to Heroku (develop)
    if: branch = develop
    script: yarn travis:ci
    deploy:
      provider: heroku
      api_key:
        secure: $HEROKU_API_KEY
      app: bardock-ng
      local_dir: dist/bardock
      skip_cleanup: true
      on:
        branch: develop
  - stage: Test Develop
    name: Curl to Dev
    if: branch = develop
    script: curl https://bardock-ng.herokuapp.com/
  - stage: deploy to production
    name: Deploy App to Firebase Hosting (master)
    if: branch = master
    script: yarn travis:ci
    deploy:
      provider: firebase
      token:
        secure: fCjNvtxN6wpqAPv4hcILMRbyvWMF+WuhR+rEphTN+4PZvbwO0LvptoTzAQsWHOXO+I5dCRhKvMkCPZFjDLttu8LW493vsBZqnh6rOZq/ERPnwSExhfeydWl0Y4cda3ByP4D/dwhm5VIACsDUAFXaylt3EJREgAjTv5VR4lVuvHAFfy/b4YxX61Z4RWuwqOB3LC4+qbIo5za7MgbrfbsEtzZAEcoK3MdNH7wv9Z9cw5wMm0fQ4Wc4guEXKAQJ4nOV89Pk0k7z9qUfB2wMdalIKR+19bW+3HSZe8mMflTQxjXz5KIP5R/JmPKHJAiEt13MWXiC4G/s+R+4zPEM5FPtxl+koepNAsuMDkj6aUKlSO9HRX/JH3lniffCATm+AxEYIbavaPR9OYFpwtn2mGxE8BL03UZ0FqOCUx8LANNpjUZGmDTxWEz184qqLj7K07DfR3X+MM5gun1KWrLzdCckz10dLYmEWgN5oNlFaK5yuQceJkkFIhQ4OzFnT13jIV3hOKIjGtlAedoXPh2H3CHrj+wl/4XOYiU8/NKzLsomm0iOonkfZV5pkS44bUHnNsazjGSjIgvum6yhSvlk6KOs4v/LA0ADvsEZuxsM3PZAIyxKjCZZFjyMTnnAqGl+sen5tKzKBhN07jSyI3iyY2D9zvzI+RyDtcy/TcGsu+7qGJ8=
      app: bardock
      local_dir: dist/bardock
      skip_cleanup: true
      on:
        branch: master
  - stage: Test Production
    name: Curl to Prod
    if: branch = master
    script: curl https://bardock-ng.firebaseapp.com/
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - krbaio3@gmail.com
    on_success: never
    on_failure: always
  slack:
    secure: fIYgEhf20QGAbzXhdHT+Xuh1MVKMZbSsCeNu+GreCXNnDJOnAug9/axNGqf7wl0IOaBa2nYPToC//6LIRiUSKBOCxBKFDNya9htuSTGStt2Dlf1xw9YF2EeqjoydgtM9Z6IbfmWQRu4O/KCsxhtISIgr8ZTOTsJaxGyf9hkSjtDmTaqzwlYQGGres8b7yZUqd+XW637OSxlKPNzq/y0gplaQl3j9Pa7u8L94f/QaU6+ErgQxaz+gLdjs3rMWb0u82brM1BGLLNn49iaJn8lV1aq8N+jQAWys7A8uiwQJ7fL4YtqCvsMuEArHRfRDRawCKU6JL5jYfxOfqnttgPhxuirSh/IfD+7hh5q0waBplo78pQJNg5LovmWRKkvkhazv1kLe+0y/v9ulSPkveTlZvTbI180TEP3qRRJAYF2iOjL77Ailq2eZwP0gPu/EJwOyWXi6SlPbk76SIAGTDhP6xR0vx7goXreHJDQeUJ+Hk9SeCzKH6UmGtzaBsvQlzYCvdyJ5NkQJX/kx09fix12dmIIS/6PLn1tEqSByx3+uId9mfcblBWN+ncK1jIAAT/0k1wtNjvjhEIBM+/vZMHsrsza/A0mU8mdDnV85qV8N6oM/ipIr9Nl6ftEquosdH+p9qRUkMe9btCtEJREUKBpIDoivsHY4d5KipzaW44F27jE=
